# Usage: KITCHEN_YAML=.kitchen.docker.yml bundle exec kitchen list
---
settings:
  parallel: true

driver:
  name: docker
  # privileged is required otherwise the container doesn't boot right
  privileged: true

provisioner:
  name: chef_solo

platforms:
- name: centos-6
  driver:
    image: centos:6
    platform: rhel
    run_command: /sbin/init
    provision_command:
      - /usr/bin/yum install -y initscripts net-tools wget
- name: centos-7
  driver:
    image: centos:7
    platform: rhel
    run_command: /usr/lib/systemd/systemd
    provision_command:
      - /bin/yum update -y
      - /bin/yum install -y initscripts net-tools wget
- name: ubuntu-14.04
  driver:
    image: ubuntu-upstart:14.04
    platform: ubuntu
    disable_upstart: false
    run_command: /sbin/init
    provision_command:
      - /usr/bin/apt-get update
      - /usr/bin/apt-get install apt-transport-https net-tools -y
- name: debian-7
  driver:
    image: debian:7
    platform: debian
    run_command: /sbin/init
    provision_command:
      - /usr/bin/apt-get update
      - /usr/bin/apt-get install apt-transport-https net-tools -y
  attributes:
    flywaydb_test:
      mysql:
        version: '5.5'
- name: debian-8
  driver:
    image: debian:8
    platform: debian
    run_command: /bin/systemd
  attributes:
    flywaydb_test:
      mysql:
        version: '5.5'

suites:
- name: default
  run_list:
    - recipe[flywaydb_test::migrate]
  attributes:
    flywaydb_test:
      params:
        password: mysql
        placeholders.test_password: test
      flyway_conf:
        user: notset
        url: jdbc:mysql://notset/mysql
        schemas: flywaydb_test
        locations: filesystem:/tmp/db
        cleanDisabled: true
        placeholders.test_user: test
      alt_conf:
        user: root
        url: jdbc:mysql://localhost/mysql
