---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.18

platforms:
  - name: centos-6.7
    driver:
      network:
      - ["forwarded_port", {guest: 3306, host: 3316}] # mysql -h 127.0.0.1 -P 3316 -u test -ptest

  - name: centos-7.1
    driver:
      network:
      - ["forwarded_port", {guest: 3306, host: 3326}]

  - name: ubuntu-14.04
    driver:
      network:
      - ["forwarded_port", {guest: 3306, host: 3346}]

  - name: windows-2012r2
    driver:
      network:
      - ["forwarded_port", {guest: 3306, host: 3356}]
    driver:
      box: dhoer/windows-2012r2

suites:
  - name: default
    run_list:
      - recipe[flywaydb_test::mysql]
      - recipe[flywaydb_test::migrate]
    attributes:
      flywaydb:
        params:
          user: root
          password: mysql
          placeholders.test_password: test
        conf:
          url: jdbc:mysql://localhost/mysql
          schemas: flywaydb_test
          locations: filesystem:/tmp/db
          placeholders.test_user: test
