---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 12

platforms:
  - name: centos-6.7
    driver:
      network:
      - ["forwarded_port", {guest: 3306, host: 3316}] # mysql -h 127.0.0.1 -P 3316 -u test -ptest

  - name: centos-7.1
    driver:
      network:
      - ["forwarded_port", {guest: 3306, host: 3326}] # mysql -h 127.0.0.1 -P 3326 -u test -ptest

  - name: ubuntu-14.04
    driver:
      network:
      - ["forwarded_port", {guest: 3306, host: 3336}] # mysql -h 127.0.0.1 -P 3336 -u test -ptest

suites:
  - name: default
    run_list:
      - recipe[flywaydb_test::migrate]
    attributes:
      flywaydb_test:
        params:
          user: root
          password: mysql
          placeholders.test_password: test
        ext_conf: /tmp/conf/ext.conf
