---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.18

platforms:
  - name: centos-6.6
  - name: centos-7.1
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: debian-7.9
  - name: windows-2012r2
    driver:
      box: dhoer/windows-2012r2

suites:
  - name: default
    run_list:
      - recipe[perforce::default]
