---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.18

platforms:
  - name: centos-6.6
  - name: centos-7.1
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: windows-2012r2
    driver:
      box: dhoer/windows-2012r2

suites:
  - name: default
    run_list:
      - recipe[flywaydb::migrate]
    attributes:
      flywaydb:
        conf:
          - url: 'jdbc:mysql://localhost/flyway_test'
            user: 'root'
            password: 'mysql'
            locations: 'filesystem:/tmp/db1'
          - url: 'jdbc:mysql://localhost/flyway_test'
            user: 'root'
            password: 'mysql'
            locations: 'filesystem:/tmp/db2'
